export const words = [
    "Cafe garden",
    "Portfolio",
    "Scroll animation",
    "Six.web",
    "tomorrow",
    "ultra",
    "life",
    "chance",
    "opportunity",
    "LoadingPage",
    "immersive",
    "Cafe garden",
    "Portfolio",
    "Scroll animation",
    "Six.web",
    "tomorrow",
    "ultra",
    "life",
    "chance",
    "opportunity",
    "LoadingPage",
    "immersive",
    "Cafe garden",
    "Portfolio",
    "Scroll animation",
    "Six.web",
    "tomorrow",
    "ultra",
    "life",
    "chance",
    "opportunity",
    "LoadingPage",
    "immersive",
    "Cafe garden",
    "Portfolio",
    "Scroll animation",
    "Six.web",
    "tomorrow",
    "ultra",
    "life",
    "chance",
    "opportunity",
    "LoadingPage",
    "immersive",
    "change",
    "Portfolio",
    "Scroll animation",
    "Six.web",
    "tomorrow",
    "ultra",
    "life",
    "chance",
    "opportunity",
    "LoadingPage",
    "immersive",
  ];
  